# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Memory.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 494)
        MainWindow.setMinimumSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Memory = QtWidgets.QOpenGLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Memory.sizePolicy().hasHeightForWidth())
        self.Memory.setSizePolicy(sizePolicy)
        self.Memory.setMinimumSize(QtCore.QSize(150, 230))
        self.Memory.setObjectName("Memory")
        self.gridLayout_2.addWidget(self.Memory, 0, 1, 1, 1)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.MemorySize = QtWidgets.QLineEdit(self.centralwidget)
        self.MemorySize.setObjectName("MemorySize")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MemorySize)
        self.SizeEnter = QtWidgets.QPushButton(self.centralwidget)
        self.SizeEnter.setObjectName("SizeEnter")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.SizeEnter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_10.setItem(2, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.HoleAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.HoleAddress.setObjectName("HoleAddress")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.HoleAddress)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.HoleSize = QtWidgets.QLineEdit(self.centralwidget)
        self.HoleSize.setObjectName("HoleSize")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.HoleSize)
        self.AddHole = QtWidgets.QPushButton(self.centralwidget)
        self.AddHole.setObjectName("AddHole")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.AddHole)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_10.setItem(6, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.NumSegments = QtWidgets.QSpinBox(self.centralwidget)
        self.NumSegments.setObjectName("NumSegments")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.NumSegments)
        self.EnterSegments = QtWidgets.QPushButton(self.centralwidget)
        self.EnterSegments.setObjectName("EnterSegments")
        self.formLayout_10.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.EnterSegments)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.formLayout_10.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_10.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Methods = QtWidgets.QComboBox(self.centralwidget)
        self.Methods.setObjectName("Methods")
        self.Methods.addItem("")
        self.Methods.addItem("")
        self.Methods.addItem("")
        self.formLayout_10.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.Methods)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_10.setItem(9, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setObjectName("Clear")
        self.formLayout_10.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.Clear)
        self.gridLayout_2.addLayout(self.formLayout_10, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Memory Size: "))
        self.MemorySize.setText(_translate("MainWindow", "0"))
        self.SizeEnter.setText(_translate("MainWindow", "Go on!"))
        self.label_2.setText(_translate("MainWindow", "Hole Start Address: "))
        self.HoleAddress.setText(_translate("MainWindow", "000"))
        self.label_3.setText(_translate("MainWindow", "Hole Size: "))
        self.HoleSize.setText(_translate("MainWindow", "0"))
        self.AddHole.setText(_translate("MainWindow", "Add Hole"))
        self.label_6.setText(_translate("MainWindow", "Num of Segments: "))
        self.EnterSegments.setText(_translate("MainWindow", "Enter Process Segments"))
        self.label_5.setText(_translate("MainWindow", "Methods Allocation:"))
        self.Methods.setItemText(0, _translate("MainWindow", "First Fit"))
        self.Methods.setItemText(1, _translate("MainWindow", "Best Fit"))
        self.Methods.setItemText(2, _translate("MainWindow", "Worst Fit"))
        self.Clear.setText(_translate("MainWindow", "Clear!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
